[package]
name = "profanity_filter"
version = "0.1.0"
authors = ["Anders Evensen"]
edition = "2018"
publish = false

[dependencies]
word_filter = {path = "../word_filter"}

[build-dependencies]
word_filter_codegen = {path = "../word_filter/word_filter_codegen"}

[features]
profane = ["damn", "hell"]
damn = []
hell = []

vulgar = ["anal", "ass", "blow-job", "fuck", "shit"]
anal = []
ass = []
blow-job = []
cunt = []
fuck = []
shit = []

offensive = ["bastard", "bitch", "faggot", "nigger", "slut"]
bastard = []
bitch = []
faggot = []
nigger = []
slut = []

middle-finger-emoji = []
