[package]
name = "profanity_filter"
version = "0.1.0"
authors = ["Anders Evensen"]
edition = "2018"
publish = false

[dependencies]
once_cell = "1.5.2"
word_filter = "0.4.0"
#word_filter = {path = "../word_filter"}
#word_filter = {git = "https://github.com/Anders429/word_filter", branch = "censor", features = ["unicode-segmentation"]}

[features]
profane = ["damn", "hell"]
damn = []
hell = []

vulgar = ["anal", "ass", "blow-job", "fuck", "shit"]
anal = []
ass = []
blow-job = []
cunt = []
fuck = []
shit = []

offensive = ["bastard", "bitch", "faggot", "nigger", "slut"]
bastard = []
bitch = []
faggot = []
nigger = []
slut = []

middle-finger-emoji = []
