[package]
name = "profanity_filter"
version = "0.1.0"
authors = ["ander"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
word_filter = {path = "../word_filter"}
