name: Compile Demo

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/demo
    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
    - run: wasm-pack build --target web
    - run: mkdir output
    - uses: canastro/copy-file-action@master
      with:
        working-directory: ./examples/demo
        source: index.html
        target: output/index.html
    - uses: canastro/copy-file-action@master
      with:
        working-directory: ./examples/demo
        source: pkg/demo.js
        target: output/demo.js
    - uses: canastro/copy-file-action@master
      with:
        working-directory: ./examples/demo
        source: pkg/demo_bg.wasm
        target: output/demo_bg.wasm
    - uses: peaceiris/actions-gh-pages@v3
      with:
        working-directory: ./examples/demo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
