name: Compile Demo

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
    - run: cd examples/demo
    - run: wasm-pack build --target web
    - run: mkdir output
    - run: mv index.html output/index.html
    - run: mv pkg/demo.js output/demo.js
    - run: mv pkg/demo_bg.wasm output/demo_bg.wasm
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
